"""Regenerate vector lettering from the project's existing Cormorant font.
Maintenance only: Python + fonttools. No network or runtime dependency.
"""
import json
import re
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

root = Path(__file__).resolve().parent.parent
name = re.search(r"recipient: '([^']+)'", (root / 'src/content.ts').read_text(encoding='utf-8')).group(1)
font = TTFont(root / 'node_modules/@fontsource/cormorant-garamond/files/cormorant-garamond-latin-400-normal.woff')
glyphs = font.getGlyphSet()
cmap = font.getBestCmap()
scale = 100 / font['head'].unitsPerEm
words = []
for word in name.split():
    letters = []
    offset = 0
    for char in word:
        glyph = glyphs[cmap[ord(char)]]
        pen = SVGPathPen(glyphs)
        glyph.draw(TransformPen(pen, (scale, 0, 0, -scale, 0, 105)))
        path = re.sub(r'-?\d+\.\d+', lambda m: str(round(float(m.group()), 2)), pen.getCommands())
        letters.append({'char': char, 'x': round(offset, 2), 'd': path, 'strokes': re.findall(r'M[^M]+', path)})
        offset += glyph.width * scale + 1.2
    words.append({'text': word, 'width': round(offset, 2), 'letters': letters})
target = root / 'src/data/nameGlyphs.ts'
target.parent.mkdir(exist_ok=True)
target.write_text('// Generated by scripts/generate-name.py from the bundled Cormorant Garamond.\nexport const nameGeometry = ' + json.dumps({'text': name, 'words': words}, ensure_ascii=False, indent=2) + ' as const\n', encoding='utf-8')
print(f'Generated {name}: {len(words)} words')
