export const content = {
  recipient: 'Esmeralda Flores',
  intro: 'Hoy quería hacerte llegar algo.',
  bloom: 'Hay cosas bonitas que encuentran la forma de llegar, incluso desde lejos.',
  garden: ['Como no puedo llevarte flores hasta donde estás…', '…hice que florecieran aquí para ti.'],
  secrets: ['Esta floreció especialmente para ti.', 'Una pequeña sorpresa, incluso desde lejos.', 'Espero haberte regalado una sonrisa.'],
  letter: [
    'Hoy me habría gustado poder entregarte estas flores personalmente.',
    'Pero como estás lejos, quise encontrar otra manera de hacértelas llegar.',
    'Espero que verlas florecer te saque una sonrisa y te alegre un poquito el día.',
    'Estas flores son para ti, Esmeralda.',
  ],
  title: ['Una flor', 'hasta donde', 'estés.'],
  gardenTitle: ['La distancia', 'también puede', 'florecer.'],
  aside: 'Un pequeño detalle para alegrarte el día.',
  brand: ['Un pequeño universo', 'hecho para ti'],
  orbit: 'Donde las estrellas se vuelven flores',
  starHint: ['Toca la estrella', 'Hay algo para ti'],
  flowerCaption: ['Un poquito de luz. Un pétalo a la vez.', 'Una rosa amarilla, para ti.'],
  bloomHint: 'Toca la rosa. Esto apenas comienza.',
  gardenHint: 'Toca una flor y descubre su pequeña sorpresa.',
  constellation: {
    discover: '¿Y esta estrella?',
    close: 'Volver a la rosa',
    caption: 'Este rincón del cielo lleva tu nombre.',
    label: 'Descubrir la constelación de Esmeralda Flores',
    loading: 'La estrella está preparando una sorpresa…',
  },
  invitation: ['También hay unas palabras para ti.', 'Abrir la carta'],
  letterDetails: {
    eyebrow: 'Un detalle desde aquí',
    signoff: 'Con cariño',
    return: 'Volver a las flores',
    monogram: 'E · F',
  },
  acts: ['Una estrella de lejos', 'Un poquito de magia', 'Un jardín para ti'],
  footer: 'Unas flores, aunque sea de una manera diferente.',
}
